/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Cragar.Drivers;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leonardo
 */
public class VistaTienda extends javax.swing.JFrame {

    /**
     * Creates new form VentanaVista
     */
    public VistaTienda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Drivers cargar= new Drivers();
    Connection conexion= cargar.acceder();
    void limpiar(){
            txtclave.setText("");
            txtnombre.setText("");
            txtprecio.setText("");
            txtfrabricante.setText("");
    }
    void mostrar1(){
        DefaultTableModel modelo=  new DefaultTableModel();
        modelo.addColumn("Clve del fabricante");
        modelo.addColumn("Nombre");
        
        
      //  DefaultTableModel modelo=  (DefaultTableModel)jTpresentar.getModel();
        modelo.setRowCount(0);
         try {
            Statement comando = conexion.createStatement();
            ResultSet registro = comando.executeQuery("select *from articulo");
            while (registro.next() ) {
                Vector vector=new Vector();
                vector.add(registro.getInt(1));
                vector.add(registro.getString(2));  
                
                modelo.addRow(vector);
            }
            
                jtMostrar.setModel(modelo);
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
    void mostrar(){
        DefaultTableModel modelo=  new DefaultTableModel();
        modelo.addColumn("Clve del articulo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Presio");
        modelo.addColumn("Clave del fabricante");
        
      //  DefaultTableModel modelo=  (DefaultTableModel)jTpresentar.getModel();
        modelo.setRowCount(0);
         try {
            Statement comando = conexion.createStatement();
            ResultSet registro = comando.executeQuery("select *from articulo");
            while (registro.next() ) {
                Vector vector=new Vector();
                vector.add(registro.getInt(1));
                vector.add(registro.getString(2));
                vector.add(registro.getString(3));
                vector.add(registro.getString(4));
               
                
                modelo.addRow(vector);
            }
            
                jtMostrar.setModel(modelo);
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        // TODO add your handling code here:
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtclave = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        txtfrabricante = new javax.swing.JTextField();
        jbtIngresar = new javax.swing.JButton();
        jbtMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMostrar = new javax.swing.JTable();
        jbtCrear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jlbclave_frabri = new javax.swing.JLabel();
        jlbnombre_fabricante = new javax.swing.JLabel();
        txtclave_fabri = new javax.swing.JTextField();
        txtnombre_fabricante = new javax.swing.JTextField();
        jbtCrer = new javax.swing.JButton();
        jbtinsert = new javax.swing.JButton();
        jbtmost = new javax.swing.JButton();
        jbtbusqueda = new javax.swing.JButton();
        jbttodo = new javax.swing.JButton();
        jbtdescuento = new javax.swing.JButton();
        jbtactualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Clave del articulo");

        jLabel2.setText("Nombre");

        jLabel3.setText("Precio");

        jLabel4.setText("Clave del fabricante ");

        txtclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclaveActionPerformed(evt);
            }
        });

        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });

        jbtIngresar.setText("Ingresar");
        jbtIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtIngresarActionPerformed(evt);
            }
        });

        jbtMostrar.setText("Mostrar");
        jbtMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMostrarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jtMostrar);

        jbtCrear.setText("Crear");
        jbtCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCrearActionPerformed(evt);
            }
        });

        jlbclave_frabri.setText("Clave frabricante");

        jlbnombre_fabricante.setText("Nombre");

        txtclave_fabri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclave_fabriActionPerformed(evt);
            }
        });

        jbtCrer.setText("Crear");
        jbtCrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCrerActionPerformed(evt);
            }
        });

        jbtinsert.setText("Insertar");
        jbtinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtinsertActionPerformed(evt);
            }
        });

        jbtmost.setText("Mostrar");
        jbtmost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtmostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbclave_frabri)
                    .addComponent(jlbnombre_fabricante))
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtclave_fabri, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(txtnombre_fabricante))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtmost)
                    .addComponent(jbtCrer)
                    .addComponent(jbtinsert))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbclave_frabri)
                            .addComponent(txtclave_fabri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbtCrer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlbnombre_fabricante)
                        .addComponent(txtnombre_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtinsert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtmost)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtbusqueda.setText("Busqueda");
        jbtbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtbusquedaActionPerformed(evt);
            }
        });

        jbttodo.setText("Busqueda Precio");
        jbttodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttodoActionPerformed(evt);
            }
        });

        jbtdescuento.setText("Descuento");
        jbtdescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtdescuentoActionPerformed(evt);
            }
        });

        jbtactualizar.setText("Actualizar");
        jbtactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtactualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtclave, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(txtnombre)
                    .addComponent(txtprecio)
                    .addComponent(txtfrabricante))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtIngresar)
                    .addComponent(jbtMostrar)
                    .addComponent(jbtCrear))
                .addGap(59, 59, 59)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtbusqueda)
                        .addGap(26, 26, 26)
                        .addComponent(jbttodo)
                        .addGap(33, 33, 33)
                        .addComponent(jbtdescuento)
                        .addGap(18, 18, 18)
                        .addComponent(jbtactualizar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtIngresar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtMostrar))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtfrabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jbtCrear)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtbusqueda, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbttodo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtdescuento)
                            .addComponent(jbtactualizar))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel5.setText("Datos articulo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclaveActionPerformed

    private void jbtIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIngresarActionPerformed
       int clave_articulo=Integer.parseInt(txtclave.getText());
       String nombre=txtnombre.getText();
       int prescio=Integer.parseInt(txtprecio.getText());
       int clve_fabricante=Integer.parseInt(txtfrabricante.getText());

         try {
            PreparedStatement insertar = conexion.prepareStatement("INSERT INTO articulo(Clave_Articulo, nombre, "
                    + "precio , clave_Fabricante) VALUES(?,?,?,?)");
            insertar.setInt(1, clave_articulo);
            insertar.setString(2, nombre);
            insertar.setInt(3, prescio);
            insertar.setInt(4, clve_fabricante);
      
            int d = insertar.executeUpdate();
            if (d > 0) {
                JOptionPane.showMessageDialog(null, "   Registro Guardado");
            } else {
                JOptionPane.showMessageDialog(null, "   Registro no  Guardado");
            }
           limpiar();
        } catch (SQLException e) {
             System.out.println("ERROR"+e);
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_jbtIngresarActionPerformed

    private void jbtMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMostrarActionPerformed
        mostrar();
    }//GEN-LAST:event_jbtMostrarActionPerformed

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed

    private void jbtCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCrearActionPerformed
try {
            String crear = "CREATE TABLE articulo (" +
			"Clave_Articulo INT NOT NULL, " +
			"nombre VARCHAR(40) NOT NULL, " +
                        "precio INT NOT NULL,"+
                        "clave_Fabricante INT NOT NULL,"+
			"PRIMARY KEY (Clave_Articulo))";
        Statement stmnt = conexion.createStatement();
	stmnt.executeUpdate(crear);
        JOptionPane.showMessageDialog(null, "tabla creada");
        } catch (SQLException e) {
            System.out.println("ERROR: "+e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jbtCrearActionPerformed

    private void txtclave_fabriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclave_fabriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclave_fabriActionPerformed

    private void jbtinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtinsertActionPerformed
        // TODO add your handling code here:int clave_articulo=Integer.parseInt(txtclave.getText());
       int clve_fabrictaen=Integer.parseInt(txtclave_fabri.getText());
       String nombre =txtnombre_fabricante.getText();
         try {
            PreparedStatement insertar = conexion.prepareStatement("INSERT INTO fabricante(Clave_fabricante, nombre)VALUES(?,?)");
                    
            insertar.setInt(1, clve_fabrictaen);
            insertar.setString(2, nombre);
            
      
            int d = insertar.executeUpdate();
            if (d > 0) {
                JOptionPane.showMessageDialog(null, "   Registro Guardado");
            } else {
                JOptionPane.showMessageDialog(null, "   Registro no  Guardado");
            }
            txtclave_fabri.setText("");
            txtnombre_fabricante.setText("");
        } catch (SQLException e) {
             System.out.println("ERROR"+e);
        }
    }//GEN-LAST:event_jbtinsertActionPerformed

    private void jbtCrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCrerActionPerformed
try {
            String crear = "CREATE TABLE fabricante(" +
			"Clave_fabricante INT NOT NULL, " +
			"nombre VARCHAR(40) NOT NULL, " +
                        
			"PRIMARY KEY (Clave_fabricante))";
        Statement stmnt = conexion.createStatement();
	stmnt.executeUpdate(crear);
        JOptionPane.showMessageDialog(null, "tabla creada");
        } catch (SQLException e) {
            System.out.println("ERROR: "+e);
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jbtCrerActionPerformed

    private void jbtmostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtmostActionPerformed
mostrar1();        // TODO add your handling code here:
    }//GEN-LAST:event_jbtmostActionPerformed

    private void jbtbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtbusquedaActionPerformed
DefaultTableModel modelo=  new DefaultTableModel();
        modelo.addColumn("nombre");
        modelo.addColumn("precio");
        
        
      //  DefaultTableModel modelo=  (DefaultTableModel)jTpresentar.getModel();
        modelo.setRowCount(0);
         try {
            Statement comando = conexion.createStatement();
            ResultSet registro = comando.executeQuery("select nombre, precio from articulo");
            while (registro.next() ) {
                Vector vector=new Vector();
                vector.add(registro.getString(1));
                vector.add(registro.getInt(2));  
                
                modelo.addRow(vector);
            }
            
                jtMostrar.setModel(modelo);
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jbtbusquedaActionPerformed

    private void jbttodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttodoActionPerformed
DefaultTableModel modelo=  new DefaultTableModel();
        modelo.addColumn("Clave del articulo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Clave del fabricante");
        
      //  DefaultTableModel modelo=  (DefaultTableModel)jTpresentar.getModel();
        modelo.setRowCount(0);
         int saldo=100;
        int sueldo=350;
         try {
            Statement comando = conexion.createStatement();
            ResultSet registro = comando.executeQuery("select * from articulo "
                    + "where precio >=" + saldo+" And precio <="+sueldo+"");
            while (registro.next() ) {
                Vector vector=new Vector();
                vector.add(registro.getInt(1));
                vector.add(registro.getString(2));
                vector.add(registro.getString(3));
                vector.add(registro.getString(4));
               
                
                modelo.addRow(vector);
            }
            
                jtMostrar.setModel(modelo);
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jbttodoActionPerformed

    private void jbtdescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtdescuentoActionPerformed
    
int fila = jtMostrar.getSelectedRow();
if(fila>=0){
   txtclave.setText(jtMostrar.getValueAt(fila,0).toString());
   txtnombre.setText(jtMostrar.getValueAt(fila, 1).toString()); 
   txtprecio.setText(jtMostrar.getValueAt(fila, 2).toString()); 
   txtfrabricante.setText(jtMostrar.getValueAt(fila, 3).toString()); 
   
}else{
    JOptionPane.showMessageDialog(null, "fila no seleccionada");
}
    }//GEN-LAST:event_jbtdescuentoActionPerformed

    private void jbtactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtactualizarActionPerformed
       int precio=450;
        int clave_articulo=Integer.parseInt(txtclave.getText());
       String nombre=txtnombre.getText();
      int sueldo=Integer.parseInt(txtprecio.getText());
       int clave_fabricante=Integer.parseInt(txtfrabricante.getText());
       String l = "UPDATE articulo " +
			"SET  Clave_Articulo= ?," +
			"nombre = ?," +
			"precio = ?," +
			"clave_Fabricante = ?" +
			"WHERE precio >= "+precio;
        try {
            if(sueldo>=450){
                
            }
        PreparedStatement actualizar = conexion.prepareStatement(l);
        actualizar.setInt(1, clave_articulo);
	actualizar.setString(2, nombre);
	actualizar.setInt(3, sueldo);
	actualizar.setInt(4, clave_fabricante);
	
	actualizar.executeUpdate();
            //PreparedStatement actualizar = conexion.prepareStatement("UPDATE cuenta set numero_cuenta='"+numero_cuenta+"'cliente='"+cliente+
               //     "'tipo_cuenta='"+tipo_cuenta+"'movimiento='"+movimiento+"'fecha='"+fecha+"saldo='"+saldo+"'WHERE tipo_cuenta='"+numero);
        
        actualizar.executeUpdate();
        
		JOptionPane.showMessageDialog(null, "datos actualizados");
                mostrar();
		limpiar();
	
        } catch (SQLException e) {
            System.out.println("ERROR:"+e);
        }
               // TODO add your handling code here:
    }//GEN-LAST:event_jbtactualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaTienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtCrear;
    private javax.swing.JButton jbtCrer;
    private javax.swing.JButton jbtIngresar;
    private javax.swing.JButton jbtMostrar;
    private javax.swing.JButton jbtactualizar;
    private javax.swing.JButton jbtbusqueda;
    private javax.swing.JButton jbtdescuento;
    private javax.swing.JButton jbtinsert;
    private javax.swing.JButton jbtmost;
    private javax.swing.JButton jbttodo;
    private javax.swing.JLabel jlbclave_frabri;
    private javax.swing.JLabel jlbnombre_fabricante;
    private javax.swing.JTable jtMostrar;
    private javax.swing.JTextField txtclave;
    private javax.swing.JTextField txtclave_fabri;
    private javax.swing.JTextField txtfrabricante;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombre_fabricante;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
